# Generated by Django 4.2 on 2024-10-15 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Conference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Conference.conference'),
        ),
    ]
